# Generated by Django 2.0.6 on 2018-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userPasswd', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True, verbose_name='用户状态')),
            ],
            options={
                'db_table': 'xpc_user',
            },
        ),
    ]
